version: '3.8'

services:
  backend:
    image: backend
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - ./apps/backend/.env
    ports:
      - "9100:9100"
    networks:
      - platform-network

  admin:
    image: admin-portal
    build:
      context: .
      dockerfile: apps/admin-portal/Dockerfile
    env_file:
      - ./apps/admin-portal/.env
    ports:
      - "3001:80" # Map host 3001 to nginx internal 80
    networks:
      - platform-network

networks:
  platform-network:
    driver: bridge
