services:
  setup:
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    command: sh -c "npm install"
    networks:
      - platform-network

  backend:
    image: node:22-alpine
    working_dir: /usr/src/app
    ports:
      - "9100:9100"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      setup:
        condition: service_completed_successfully
    command: sh -c "npm run dev:backend"
    networks:
      - platform-network

  admin:
    image: node:22-alpine
    working_dir: /usr/src/app
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    depends_on:
      setup:
        condition: service_completed_successfully
    command: sh -c "npm run dev:admin"
    networks:
      - platform-network

volumes:
  node_modules:


networks:
  platform-network:
    driver: bridge
