services:
  app:
    image: backend
    build:
      context: ../../ # Requires running docker-compose build from the context of this file, or better yet, building via the sh script first.
      dockerfile: apps/backend/Dockerfile
    ports:
      - "9100:9100"
    networks:
      - wellness-network

networks:
  wellness-network:
    driver: bridge
